In [13]:
import numpy as np
import pandas as pd
df = pd.read_csv('creditcard.csv')

In [14]:
df.sample(5)

Time        V1        V2        V3        V4        V5        V6  \
80333    58438.0 -3.430289 -7.486714 -2.663386  3.079417 -2.279894  0.930905   
253098  156088.0 -1.479855  0.635113  0.584343 -0.853101 -0.342483 -0.161733   
196070  131349.0 -0.154391  0.976556  0.403211 -0.464702  1.188820 -0.394527   
17226    28544.0  1.165972 -0.144833 -0.097223  1.736661  1.698404  4.646759   
67488    52558.0 -0.645652  0.514583  2.641741  1.699048 -0.855281  0.343118   

              V7        V8        V9  ...       V21       V22       V23  \
80333   3.169039 -0.446583 -0.193115  ...  1.446479 -1.178465 -2.250317   
253098 -0.481814  0.925337  0.295348  ...  0.339107  0.740505 -0.279617   
196070  1.159756 -0.236675 -0.625685  ... -0.260252 -0.571745 -0.083470   
17226  -1.189485  1.205305  0.333703  ... -0.032082  0.113416 -0.165203   
67488   0.199096  0.151480 -0.116649  ...  0.061475  0.244616 -0.038835   

             V24       V25       V26       V27       V28   Amount  Class  
80333  -0.219605 -0.156845 -0.476219 -0.440820  0.408040  2387.52      0  
253098  0.637700 -0.068293  0.072914 -0.195455 -0.068935    29.20      0  
196070  0.683206 -0.512731  0.154737 -0.068165 -0.050068     1.98      0  
17226   1.045671  0.774785  0.228583  0.050559  0.020283     1.52      0  
67488   0.392719  0.165020 -0.127255  0.128446  0.109698    95.00      0  

[5 rows x 31 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [16]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [17]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

### Cross Validation: KFold
### Hyperparameter tuning: GridSearchCV

In [18]:
from sklearn.model_selection import train_test_split, KFold, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [22]:
lr = LogisticRegression()
grid = {'C':10.0**np.arange(-2,3), 'penalty':['l1','l2']}
cv = KFold(n_splits=5, shuffle=False, random_state=None)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [24]:
model = GridSearchCV(lr, grid, cv=cv, n_jobs=-1, scoring='f1_macro')
model.fit(X_train, y_train)

c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\users\asus\appdata\local\programs\python\pyth

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [30]:
model.best_params_

{'C': 1.0, 'penalty': 'l2'}

In [25]:
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85253    48]
 [   42   100]]
0.9989466661985184
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85301
           1       0.68      0.70      0.69       142

    accuracy                           1.00     85443
   macro avg       0.84      0.85      0.84     85443
weighted avg       1.00      1.00      1.00     85443



In [31]:
class_weight = dict({0: 1, 1: 100})

In [32]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(class_weight=class_weight)
model.fit(X_train, y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [33]:
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85297     4]
 [   33   109]]
0.9995669627705019
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85301
           1       0.96      0.77      0.85       142

    accuracy                           1.00     85443
   macro avg       0.98      0.88      0.93     85443
weighted avg       1.00      1.00      1.00     85443



### Under Sampling

In [34]:
from imblearn.under_sampling import NearMiss
from collections import Counter

In [35]:
ns = NearMiss(0.8)
X_train_ns, y_train_ns = ns.fit_resample(X_train, y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\imblearn\utils\_validation.py:586: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


The number of classes before fit Counter({0: 199014, 1: 350})
The number of classes after fit Counter({0: 437, 1: 350})


In [36]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train_ns, y_train_ns)

RandomForestClassifier()

In [37]:
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[72994 12307]
 [   13   129]]
0.855810306286062
              precision    recall  f1-score   support

           0       1.00      0.86      0.92     85301
           1       0.01      0.91      0.02       142

    accuracy                           0.86     85443
   macro avg       0.51      0.88      0.47     85443
weighted avg       1.00      0.86      0.92     85443



### Over Sampling

In [39]:
from imblearn.over_sampling import RandomOverSampler

In [40]:
os = RandomOverSampler(0.5)
X_train_os, y_train_os = os.fit_resample(X_train, y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_os)))

c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\imblearn\utils\_validation.py:586: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


The number of classes before fit Counter({0: 199014, 1: 350})
The number of classes after fit Counter({0: 199014, 1: 99507})


In [41]:
model = RandomForestClassifier()
model.fit(X_train_os, y_train_os)

RandomForestClassifier()

In [42]:
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85296     5]
 [   31   111]]
0.9995786664794073
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85301
           1       0.96      0.78      0.86       142

    accuracy                           1.00     85443
   macro avg       0.98      0.89      0.93     85443
weighted avg       1.00      1.00      1.00     85443



### SMOTETomek

In [43]:
from imblearn.combine import SMOTETomek

In [44]:
os = SMOTETomek(0.5)
X_train_os, y_train_os = os.fit_resample(X_train, y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_os)))

c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\imblearn\utils\_validation.py:586: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


The number of classes before fit Counter({0: 199014, 1: 350})
The number of classes after fit Counter({0: 198104, 1: 98597})


In [45]:
model = RandomForestClassifier()
model.fit(X_train_os, y_train_os)

RandomForestClassifier()

In [46]:
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85284    17]
 [   23   119]]
0.9995318516437859
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85301
           1       0.88      0.84      0.86       142

    accuracy                           1.00     85443
   macro avg       0.94      0.92      0.93     85443
weighted avg       1.00      1.00      1.00     85443

